### PR TITLE
Add getports for platforms other than windows

### PR DESCRIPTION
**Pull request by gmkarl**

### CODE REVIEW

**Comment by billhsu** [comment]
@gmkarl thanks for the PR. I'll verify it and merge later.

**Comment by billhsu** [comment]
@rwmcintosh @adilek can you help review this as well?

**Comment by billhsu** [comment]
@rwmcintosh @adilek can you help review this as well?

**Comment by adilek** [comment]
Sorry @billhsu 
I have no necessary tools. I moved to another country.

**Comment by Gregwar** [comment]
I've tested it, it compiles and work (Ubuntu 15.04)
Sounds good to me

**Comment by billhsu** [comment]
@Gregwar :+1:

**Pull request merged**
